# Generated by Django 3.0.8 on 2020-07-23 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('AV', 'Available'), ('CO', 'Checked out')], default='AV',
                                          max_length=2)),
                ('status', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'bookstatus',
                'ordering': ['status'],
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('AB', 'Alberta'), ('BC', 'British Columbia'), ('MB', 'Manitoba'),
                                                   ('NB', 'New Brunswick'), ('NL', 'Newfoundland and Labrador'),
                                                   ('NS', 'Nova Scotia'), ('NT', 'Northwest Territories'),
                                                   ('NU', 'Nunavut'), ('ON', 'Ontario'), ('PE', 'Prince Edward Island'),
                                                   ('QC', 'Quebec'), ('SK', 'Saskatchewan'), ('YT', 'Yukon')],
                                          default='BC', max_length=2)),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'provinces',
                'ordering': ['name'],
            },
        ),
    ]
