# Generated by Django 3.0.8 on 2020-09-15 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20200727_2227'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookStatus',
        ),
    ]
