# Generated by Django 3.2 on 2021-04-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_bookstatus_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstatus',
            name='code',
            field=models.CharField(choices=[('AV', 'Available'), ('CO', 'Checked out'), ('LO', 'Locked'),
                                            ('RM', 'Removed'), ('RE', 'Requested')],
                                   default='AV', max_length=2, unique=True),
        ),
    ]
