# Generated by Django 3.2 on 2021-10-05 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_bookstatus_code'),
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageoneone',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='book',
                                    to='books.book'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messageoneone',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
