# Generated by Django 3.2 on 2021-10-06 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_messagetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageoneone',
            name='msg_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='msg_type',
                                    to='messaging.messagetype'),
            preserve_default=False,
        ),
    ]
